### PR TITLE
Limit the featured queryset to 3 items.

### PR DESCRIPTION
**Pull request by akatsoulas**

### CODE REVIEW

**Comment by akatsoulas** [comment]
Partial fix of  #394

**Comment by comzeradd** [comment]
Let's wait a bit for @m-branson. I think that due to the new design we may only want 2 featured entities here.

**Comment by akatsoulas** [comment]
Right now, the homepage displays all the featured clubs (>3). Let's limit to 3 and we can change that in the future if needed.

**Comment by johngian** [comment]
For now i suggest we just ``order_by('?')`` to get random featured objects and just select the first 3.

**Pull request merged**
