### PR TITLE
Initial implementation of  top-level navigation menu

### PR DESCRIPTION
**Pull request by comzeradd**

### CODE REVIEW

**Comment by akatsoulas** [comment]
This PR needs a rebase.

**Comment by comzeradd** [comment]
PR rebased

**Comment by comzeradd** [comment]
PR rebased and it's now based on Phase 1 Design. One thing missing is the new OS Clubs logo. We'll add it on a different PR once we have it.

**Comment by comzeradd** [comment]
> Can we also get nested submenus from this?

Not yet, because we need to figure out the design for this first. I opened #380 to track this.

**Pull request merged**
