### PR TITLE
Update the OSSN logo.

### PR DESCRIPTION
**Pull request by akatsoulas**

### CODE REVIEW

**Comment by akatsoulas** [comment]
@hidde r?

**Comment by hidde** [comment]
@akatsoulas These files are currently PNGs, should the new ones be PNGs too?

**Comment by akatsoulas** [comment]
@hidde the PNGs were manually uploaded through the admin interface (the logo field is dynamic). Thoughts?

**Comment by johngian** [comment]
@akatsoulas I am not sure if by changing this svg you are actually changing the logo in the website. Better said, i am not sure if we use these svg's at all.

``` ➜ grep -iR "clubs-black.svg"`` returns no result

**Comment by akatsoulas** [comment]
I will update the PR and basically drop these entries completely. We can update the PNGs through the admin interface

**Pull request closed without merging**
